name: fastqc-pipeline
channels:
  - conda-forge
    - bioconda
      - defaults
      dependencies:
        - python=3.9.13
          - fastqc=0.11.9
            - multiqc=1.14.0
              - fastp=0.23.2
                - pip
                  - pip:
                        - "" # add extra Python packages here if needed
